baseURL = "https://joshforb.es/"
languageCode = "en-us"
title = "joshforb.es"

[Params]
  Author = "Josh Forbes"
  twitter = "forbesdeveloper"
  disqusShortname = "joshforb-es"

[menu]
    [[menu.main]]
      name       = "github"
      url        = "https://github.com/joshforbes"

    [[menu.main]]
      name       = "twitter"
      url        = "https://twitter.com/forbesdeveloper"